### ISSUE TITLE
Ask for location permission

### ISSUE THREAD

**Issue by lmilunovic** [Ladislav92/Mine-Field-Alarm-Android-Politech#10]
The user should be explicitly asked for permission for location if the app has no permission. Right now that is not implemented and it should be.

**Comment by raragod** [comment]
Would like to try to fix this!

**Comment by lmilunovic** [comment]
Yeah, go on. Haven't touched the project for long time already, honestly.

**Comment by raragod** [comment]
Looks like the required permissions are already defined in the manifest. I took out "android.permission.ACCESS_COARSE_LOCATION " and kept the "android.permission.ACCESS_FINE_LOCATION" since you only need one of those. Now trying to figure out how to create a PR :)
